version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WEB_CONCURRENCY=1
      - GUNICORN_MAX_WORKERS=2
      - GUNICORN_MIN_WORKERS=1
      - MAX_WORKER_MEMORY_MB=512
      - MEMORY_LIMIT=70
    depends_on:
      - redis
    volumes:
      - ./:/app
    restart: unless-stopped

  worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    volumes:
      - ./:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M

  beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    volumes:
      - ./:/app
    restart: unless-stopped

  flower:
    build: .
    command: celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
      - worker
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: