version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - WEB_CONCURRENCY=1
      - GUNICORN_MAX_WORKERS=2
      - GUNICORN_MIN_WORKERS=1
      - MAX_WORKER_MEMORY_MB=2048 # เพิ่มค่า
      - CPU_THRESHOLD_UP=85
      - CPU_THRESHOLD_DOWN=40
      - MEMORY_THRESHOLD=70
    depends_on:
      - redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G

  worker:
    build: .
    command: celery -A app.core.celery_app worker -Q default,face_detection --loglevel=info --concurrency=1 --max-memory-per-child=2048000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1.5G

  beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
    volumes:
      - ./:/app
    restart: unless-stopped

  flower:
    build: .
    command: celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
      - worker
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server --appendonly yes
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 300
      --timeout 0
    restart: unless-stopped

volumes:
  redis-data: